/**
 * Standardized error codes for API responses.
 * Frontend can use these to display localized/specific error messages.
 */
export enum ErrorCode {
  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_INSUFFICIENT_ROLE = 'AUTH_INSUFFICIENT_ROLE',

  // Attendance
  ATTENDANCE_ALREADY_CHECKED_IN = 'ATTENDANCE_ALREADY_CHECKED_IN',
  ATTENDANCE_ALREADY_CHECKED_OUT = 'ATTENDANCE_ALREADY_CHECKED_OUT',
  ATTENDANCE_NO_CHECKIN_TODAY = 'ATTENDANCE_NO_CHECKIN_TODAY',
  ATTENDANCE_FRAUD_BLOCKED = 'ATTENDANCE_FRAUD_BLOCKED',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_NO_BRANCH = 'USER_NO_BRANCH',

  // Branch
  BRANCH_NOT_FOUND = 'BRANCH_NOT_FOUND',

  // Leave
  LEAVE_NOT_FOUND = 'LEAVE_NOT_FOUND',
  LEAVE_ALREADY_PROCESSED = 'LEAVE_ALREADY_PROCESSED',

  // Rate Limit
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
